EXEC = libtemplog.a

OBJECTS = \
	print.o \

include ../../../Makefile.common
include $(MAKER_ROOT)/Makefile.gcc

CFLAGS += \
	-I../../src/include/libtemplog \
	-I$(WISP_BASE_ROOT) \
	-I$(LIBIO_ROOT)/src/include \

VPATH = ../../src
